news:
  urls:
    # - https://tuoitre.vn/
    - https://www.tinnhanhchungkhoan.vn/
    - https://vnexpress.net/
    - https://nguoiquansat.vn/
number_of_news: 15
use_images: True
memoize_articles: True