news:
  urls:
    - https://vnexpress.net/
    - https://theinvestor.vn/
    - https://dantri.com.vn/
    - https://www.tinnhanhchungkhoan.vn/
  block_list :
    - "#"
    - "comment"
    - "newsbtc.com/news/"
number_of_news: 5
use_images: True
memoize_articles: False
theme: dark
page_size: 5
